### ISSUE TITLE
The Replay Manager freezes

### ISSUE THREAD

**Issue by s3rialthrill3r** [0xNeffarion/CELO-Enhanced#1]
Whenever I click on the the Replay Manager, it says 'Parsing Replays Information' and then the loading bar and CELO freezes, giving me a message saying that it has stopped working.

**Comment by 0xNeffarion** [comment]
I will need you to provide me the contents of the latest log file when that happens. You can open the logs folder in the UI on Help menu up top.

**Comment by s3rialthrill3r** [comment]
Sure. Here it is:
[CELO_LOG_17.log](https://github.com/0xNeffarion/CELO-Enhanced/files/1390822/CELO_LOG_17.log)

**Comment by 0xNeffarion** [comment]
Thanks for the log, I have updated the replay manager, can you please verify it works now?

**Comment by s3rialthrill3r** [comment]
Unfortunately, I'm still getting the same issue. Here is another log: 
[CELO_LOG_26.log](https://github.com/0xNeffarion/CELO-Enhanced/files/1393087/CELO_LOG_26.log)
