### ISSUE TITLE
Ladder rank

### ISSUE THREAD

**Issue by yehnet** [0xNeffarion/CELO-Enhanced#2]
Hi,

After the last update (april/march 2021) , on ladder rank there's some static number for every user (something between 90000 ~ 9000000), and not the rank number(1~4000). 
(I get the same number everytime)

*celo v. 1.2.0
*coh2 v. 4.0.0.23915

**Comment by RintFosk** [comment]
I'm having the same issue, please fix?

**Comment by 0xNeffarion** [comment]
> I'm having the same issue, please fix?

Relic changed the way the rankings are displayed internally in the log files. There's no way to ensure the ranks are accurate anymore besides 1v1s
